#!/bin/bash

# Setup and validate arguments
psql_host=$1
psql_port=$2
db_name=$3
psql_user=$4
psql_password=$5

# Check # of args
if [ "$#" -ne 5 ]; then
    echo "Illegal number of parameters"
    exit 1
fi

# Parse host hardware specifications using bash commands
# Assign the parsed outputs to variables

# Construct the INSERT statement from specification variables

# Execute the INSERT statement through the psql CLI tool

